# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'FarmProject' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for FarmProject
  pod 'GoogleMaps'
  pod 'GooglePlaces'
  pod 'FBSDKLoginKit'
  pod 'FacebookCore'
  pod 'FacebookLogin'
  pod 'Alamofire'
  pod 'Kingfisher', '~> 5.0'
  pod 'Firebase/Core'
  pod 'Firebase/Firestore'
  pod 'DropDown'
  pod 'Firebase/Auth'
  pod 'Kanna'
  pod 'SwiftyJSON'
  pod 'NVActivityIndicatorView'


end
